### ISSUE TITLE
google push 报错

### ISSUE THREAD

**Issue by 2176608** [tardis-ksh/hexo-seo-submit#8]
如图：
![6](https://github.com/user-attachments/assets/752e6cc9-87fd-4972-a7af-b95fc804e4f1)
已配置环境变量，且配置google_private_key时去除了引号。

**Comment by 2176608** [comment]
这里也配置了：
![image](https://github.com/user-attachments/assets/0c476c9c-32f3-4a03-9163-7f6cac871785)

**Comment by Kshao123** [comment]
hello，刚测试了下是可以使用的，[hexo-seo-submit-demo](https://github.com/tardis-ksh/hexo-seo-submit-demo)，[actions](https://github.com/tardis-ksh/hexo-seo-submit-demo/actions/runs/10038585296/job/27740802913)。请重新确认下 `google_private_key` 和 `google_client_email` 的配置。这两个 `key` 在 `json` 中直接复制出来就好了，都不需要引号。
<img width="849" alt="截屏2024-07-22 下午5 45 36" src="https://github.com/user-attachments/assets/378b6768-613d-4d1f-8ecf-69b43a406cb5">
<img width="931" alt="截屏2024-07-22 下午5 46 13" src="https://github.com/user-attachments/assets/63e22234-de4e-4427-84c4-f524b2a97186">
<img width="319" alt="截屏2024-07-22 下午5 49 24" src="https://github.com/user-attachments/assets/f3e95e62-5f57-4d45-900b-434eaa8d8dc4">
